### PR TITLE
fixed configure error on aarch64 platform

### PR DESCRIPTION
**Pull request by alephman**
Fixed the error of "configure: error: cannot guess build type" on aarch64 platform.

### CODE REVIEW

**Comment by alephman** [comment]
I signed it!

**Comment by npanpaliya** [comment]
@alephman , Thanks for creating this pull request. We also wanted this change to be in farmhash so that we can build it on ppc64le architecture. Request @googlebot to kindly merge this PR.

**Comment by npanpaliya** [comment]
@googlebot , could you please let me know the status of this PR? We needed it for ppc64le too.

**Comment by vrv** [comment]
@geoffpike ping?

**Comment by npanpaliya** [comment]
Hello @alephman , Any idea what is holding back this request to get merged?

**Pull request merged**
